### ISSUE TITLE
categories 和 tags 索引页面的路径问题

### ISSUE THREAD

**Issue by ttchengcheng** [rujews/maupassant-hugo#10]
在 config.toml 里设置了 baseURL, 比如 baseURL = "https://xxxx.github.io/blog"

hugo 编译出来的 categories 和 tags 索引页面的路径应该是 
`https://xxxx.github.io/blog/tags/tagname` 和 `https://xxxx.github.io/blog/categories/categoryname `

但现在的结果是 (少了 **"blog/"**), 导致 404
`https://xxxx.github.io/tags/tagname` 和 `https://xxxx.github.io/categories/categoryname`

我看了一下, 可能是因为
layouts/partials/ 里面的 tags.html 和 categories.html 这两个文件路径计算问题

这段
`<a href="{{ "/tags/" | absLangURL }}...</a>`

改成

`<a href="{{ "tags/" | absLangURL }}...</a>` 

就好了( tags 前面那个斜杠去掉) 

PS: 这个主题很棒, 非常感谢

**Comment by github-young** [comment]
感谢，我今天也遇到了同样的问题
