### ISSUE TITLE
你好，请问我使用nginx 访问 hugo 生成的public目录，中间的文章内容没有渲染出来

### ISSUE THREAD

**Issue by Mfk759853063** [rujews/maupassant-hugo#12]
<img width="1447" alt="wx20181122-151820 2x" src="https://user-images.githubusercontent.com/4027519/48887349-f093e080-ee69-11e8-907e-0913f9154803.png">

**Comment by Mfk759853063** [comment]
这个问题我解决了，是因为我没有把draft设置为false的原因。
还有个问题就是搜索感觉没用啊？

**Comment by rujews** [comment]
> 这个问题我解决了，是因为我没有把draft设置为false的原因。
> 还有个问题就是搜索感觉没用啊？

静态网页没有搜索的。这个搜索是基于Google的 Site搜索
