### ISSUE TITLE
我想让副标题内容换行

### ISSUE THREAD

**Issue by pkptzx** [rujews/maupassant-hugo#14]
请不要鄙视我这个问题...
我想让副标题内容换行

**Comment by rujews** [comment]
> 请不要鄙视我这个问题...
> 我想让副标题内容换行

副标题？哪个位置的？

**Comment by pkptzx** [comment]
就是顶部标题下面的字.
就是你博客
"专注于Android、Java、Go语言(golang)、移动互联网、项目管理、软件架构"
我想加句话,但太长了,想换行.

**Comment by pkptzx** [comment]
@rujews

**Comment by rujews** [comment]
比较小众，又不太好支持，暂时不会支持 @pkptzx
