### ISSUE TITLE
如何在每篇文章末尾添加版权信息与分享按钮

### ISSUE THREAD

**Issue by zouzhitao** [rujews/maupassant-hugo#17]
你好，一个前端小白，也喜欢这款主题，我看了你的blog是在末尾有版权信息的，能否问问如何添加版权信息以及分享的功能啊

**Comment by rujews** [comment]
这个是我文章里自己加的  @zouzhitao

**Comment by zouzhitao** [comment]
想问问dalao，具体怎么加啊？，不会写每篇文章的时候都自己加吧 @rujews

**Comment by rujews** [comment]
Hugo 有个 archetypes 目录，这里可以创建MD文件模版，你创建一个，在这个模板里加上自己的版权，这样你每次hugo new post的时候，使用的就是这个模板。 @zouzhitao

**Comment by CaiJingLong** [comment]
我的做法是fork 这个theme库,然后修改footer.html
在里面添加

![image](https://user-images.githubusercontent.com/14145407/49875558-400f7000-fe5c-11e8-97cc-f7c98ad673a3.png)

[参考链接]
(https://github.com/CaiJingLong/maupassant-hugo/blob/715f7176c14a49268eec830855af2250210cf988/layouts/partials/footer.html#L12-L13)

**Comment by zouzhitao** [comment]
多谢两位
