### ISSUE TITLE
如何给代码添加行号？

### ISSUE THREAD

**Issue by buzzers** [rujews/maupassant-hugo#2]
我尝试使用prism的line number插件，但是任然无法显示行号，但是右边多了一栏，我不是很清楚这是怎么回事。

**Comment by JokerQyou** [comment]
我找到最简单的解决办法是把 `{{ .Content }}` 改为：

```
{{ .Content | replaceRE "<pre>" "<pre class=\"line-numbers\">" | safeHTML }}
```

但是这个方法看起来一点都不优雅……而且总觉得有点安全隐患

**Comment by rujews** [comment]
@JokerQyou 恩，因为Hugo推荐的是内置的 Chroma 的方式，开渲染代码高亮。

**Comment by JokerQyou** [comment]
我最后用魔改 Prism 的 line-numbers 插件代码实现了……虽说还是有点脏。就是去掉了 js 里面对于那个 class 的需求。

**Comment by liuhan907** [comment]
问题是内置的那个Chroma生成的东西总是有问题，样式冲突还是怎么回事我不是很清楚。

**Comment by fcying** [comment]
写代码的时候 用
```shell 框起来(用go c 测试都有)就有行号了...
只用```的时候没有

**Comment by rujews** [comment]
恩，要有指定对应的语言 @fcying
