### ISSUE TITLE
$$Tex code$$, 块内公式换行问题，请问你们是怎样解决的呢？

### ISSUE THREAD

**Issue by zouzhitao** [rujews/maupassant-hugo#21]
插入 latex 公式，如果$$Tex code$$ 块内有多行的时候，直接用 `\\`  无法显示，请问你们是怎么解决这个问题的呢？

比如，我插入以下公式

```
$$
\begin{align}
E[0] &=\frac{\sum_{i=1}^nv_i}{n}\\
E[1] &= \frac{j^2}{n^2}\frac{\sum_{k<=j}v_i}{j} + \frac{(n-j)(n+j)}{n^2}\frac{\sum_{i>j}v_i}{n-j}\\
&= \frac{j\sum_{k<=j}v_i}{n^2}+\frac{(n+j)\sum_{i>j}v_i}{n^2}\\
&= \frac{\sum_{i>j}v_i}{n} + \frac{j\sum_iv_i}{n^2}\\
&=\frac{\sum_{i>j}v_i+jE[0]}{n}\\
\end{align}
$$
```

然后 无法显示，查看网页源码是,

```

<p>$$
   \begin{align}
   E[0] &amp;=\frac{\sum_{i=1}^nv_i}{n}<br />
   E[1] &amp;= \frac{j^2}{n^2}\frac{\sum_{k&lt;=j}v_i}{j} + \frac{(n-j)(n+j)}{n^2}\frac{\sum_{i&gt;j}v_i}{n-j}<br />
   &amp;= \frac{j\sum_{k&lt;=j}v<em>i}{n^2}+\frac{(n+j)\sum</em>{i&gt;j}v_i}{n^2}<br />
   &amp;= \frac{\sum_{i&gt;j}v_i}{n} + \frac{j\sum_iv_i}{n^2}<br />
   &amp;=\frac{\sum_{i&gt;j}v_i+jE[0]}{n}<br />
   \end{align}
  $$</p>
```

后面又换行符但是无法显示换行

**Comment by rujews** [comment]
@guader 有时间的话看看这个问题 。

**Comment by guader** [comment]
> 插入 latex 公式，如果$$Tex code$$ 块内有多行的时候，直接用 `\\` 无法显示，请问你们是怎么解决这个问题的呢？
> 
> 比如，我插入以下公式
> 
> ```
> $$
> \begin{align}
> E[0] &=\frac{\sum_{i=1}^nv_i}{n}\\
> E[1] &= \frac{j^2}{n^2}\frac{\sum_{k<=j}v_i}{j} + \frac{(n-j)(n+j)}{n^2}\frac{\sum_{i>j}v_i}{n-j}\\
> &= \frac{j\sum_{k<=j}v_i}{n^2}+\frac{(n+j)\sum_{i>j}v_i}{n^2}\\
> &= \frac{\sum_{i>j}v_i}{n} + \frac{j\sum_iv_i}{n^2}\\
> &=\frac{\sum_{i>j}v_i+jE[0]}{n}\\
> \end{align}
> $$
> ```
> 然后 无法显示，查看网页源码是,
> 
> ```
> 
> <p>$$
>    \begin{align}
>    E[0] &amp;=\frac{\sum_{i=1}^nv_i}{n}<br />
>    E[1] &amp;= \frac{j^2}{n^2}\frac{\sum_{k&lt;=j}v_i}{j} + \frac{(n-j)(n+j)}{n^2}\frac{\sum_{i&gt;j}v_i}{n-j}<br />
>    &amp;= \frac{j\sum_{k&lt;=j}v<em>i}{n^2}+\frac{(n+j)\sum</em>{i&gt;j}v_i}{n^2}<br />
>    &amp;= \frac{\sum_{i&gt;j}v_i}{n} + \frac{j\sum_iv_i}{n^2}<br />
>    &amp;=\frac{\sum_{i&gt;j}v_i+jE[0]}{n}<br />
>    \end{align}
>   $$</p>
> ```
> 后面又换行符但是无法显示换行

请在console看下该页面是否成功引入了以下js：
<script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML' async></script>

或者能否提供一下您的源网站地址呢？

**Comment by guader** [comment]
另外，在官方文档中有如下描述：
```
Some content-management systems use the backslash (\) as a special character for “escaping”
other characters, but TeX uses this character to indicate a macro name. In such systems,
you may have to double the backslashes in order to obtain a single backslash in your HTML page.
For example, you may have to do

\\begin{array}{cc}
  a & b \\\\
  c & c
\\end{array}
to get an array with the four entries a, b, c, and d.
Note in particular that if you want \\ you will have to double both backslashes, giving \\\\.
```
地址：http://docs.mathjax.org/en/latest/tex.html#tex-and-latex-math-delimiters
所以请尝试使用`\\`代替`\`，比如我是这样写的：
```
$$\begin{align\*}
\frac{\partial}{\partial\theta\_j}J(\theta\_0,\theta\_1) &= \frac{\partial}{\partial\theta\_j}\frac{1}{2m}\sum\_{i=1}^m\big(h\_\theta(x^{(i)})-y^{(i)}\big)^2 \\\\\\
&= \frac{\partial}{\partial\theta\_j}\frac{1}{2m}\sum\_{i=1}^m\big(\theta\_0+\theta\_1x^{(i)}-y^{(i)}\big)^2
\end{align\*}$$
```
希望有所帮助

**Comment by zouzhitao** [comment]
ok 问题已解决 谢谢 @guader @rujews 

**简单总结解决方案:**

1.  将所有的下标 `_` 用 `\_` 转义，比如: `\sum_` - > `\sum\_`
2.  将所有的换行 `\\` 也用 `\`转义，注意这里改为 `\\\\\\` 即，6个换行符号 
3.  把 `align` 改为 `align\*`

以上解决方案总结自 @guader

**Comment by blogless** [comment]
> ok 问题已解决 谢谢 @guader @rujews
> 
> **简单总结解决方案:**
> 
> 1. 将所有的下标 `_` 用 `\_` 转义，比如: `\sum_` - > `\sum\_`
> 2. 将所有的换行 `\\` 也用 `\`转义，注意这里改为 `\\\\\\` 即，6个换行符号
> 3. 把 `align` 改为 `align\*`
> 
> 以上解决方案总结自 @guader

解决markdown与mathjax的冲突，有个不用修改 latex 公式的办法： 
用`<div></div>` 把公式包起来，这样markdown引擎会认为这是用户手动插入的html，就不会作为markdown格式来处理，mathjax拿到的就是没有打乱的latex公式，从而正常显示公式。
需要注意的是 `<div></div>` 前后要加空行

**Comment by Buezw** [comment]
> > ok 问题已解决 谢谢 @guader @rujews
> > **简单总结解决方案:**
> > 
> > 1. 将所有的下标 `_` 用 `\_` 转义，比如: `\sum_` - > `\sum\_`
> > 2. 将所有的换行 `\\` 也用 `\`转义，注意这里改为 `\\\\\\` 即，6个换行符号
> > 3. 把 `align` 改为 `align\*`
> > 
> > 以上解决方案总结自 @guader
> 
> 解决markdown与mathjax的冲突，有个不用修改 latex 公式的办法： 用`<div></div>` 把公式包起来，这样markdown引擎会认为这是用户手动插入的html，就不会作为markdown格式来处理，mathjax拿到的就是没有打乱的latex公式，从而正常显示公式。 需要注意的是 `<div></div>` 前后要加空行

感谢
