### ISSUE TITLE
自定义文章摘要长度

### ISSUE THREAD

**Issue by yrq110** [rujews/maupassant-hugo#22]
# 问题
在目前的`layouts/index.html`与`layouts/_default/taxonomy.html`模板中，摘要部分采用的是截断固定文本长度的方式：
```html
...
<div class="post-content">
        {{ .Content | markdownify | truncate 180 }}
    <p class="readmore"><a href="{{ .Permalink }}">阅读全文</a></p>
</div>
...
```

# 建议
使用[.Summary](https://gohugo.io/content-management/summaries)页面变量，这样就可以识别文章中的[`<!--more-->`](https://gohugo.io/content-management/summaries#manual-summary-splitting)标记了，

```html
...
<div class="post-content">
        {{ .Summary | markdownify }}
    <p class="readmore"><a href="{{ .Permalink }}">阅读全文</a></p>
</div>
...
```
也可以在`config.toml`中使用[`summaryLength`](https://gohugo.io/content-management/summaries#automatic-summary-splitting)自动限制摘要的元素数量。
```toml
summaryLength = 10 # default 70
```

**Comment by rujews** [comment]
的确，好主意  @yrq110

**Comment by rujews** [comment]
已经加入了这个功能。从原来的文章摘要变为Hugo内置的摘要后，存在一个问题，就是Hugo的摘要时没有HTML格式的，都是纯文本，这个变更可能会引起两个效果。

1. 原来用的朋友会不习惯，因为没有了格式，都是纯文本了。
2. 原来摘要中有标题的，这次变更后，可以区分清楚文章内容和标题了，因为摘要时纯文本了，层次更清晰。

最后，为了和Hugo保持兼容，所以还是选择了Hugo内置的摘要功能，希望大家可以理解。
