### ISSUE TITLE
添加文章评论遇到问题

### ISSUE THREAD

**Issue by binhaifgs1** [rujews/maupassant-hugo#23]
是不是需要在文章的front-matter中添加什么才能显示评论框

**Comment by binhaifgs1** [comment]
@rujews 感谢，我不是IT人，你这个theme真好用，我做了一个工程管理的小站点，看你的theme好几天了，今天突然开窍了，现在可以用disqus、utterance、livere进行评论，我挨着试试看哪个适合。感谢大佬帮助。

**Comment by rujews** [comment]
赞 @binhaifgs1

**Comment by binhaifgs1** [comment]
maupassant主题集成的google搜索，一些同事没法用，我想在页面的顶端添加一个algolia搜索插件，google仍保留，大佬能指点一下吗，另外这样会不会破坏页面美感啊，希望大佬不要介意。

**Comment by rujews** [comment]
可以多支持几种，自己在config.tml里选择。

**Comment by zoux86** [comment]
@binhaifgs1  你使用utterance成功了吗。我安装教程安装后，文章没有显示评论。页面显示这种情况：
![image](https://user-images.githubusercontent.com/14087435/69482066-b4ff6e00-0e51-11ea-9f8b-55f20d41f3aa.png)

**Comment by kasnet** [comment]
@zoux86  问下  你这个问题解决了,  我也出现这个情况了
