### ISSUE TITLE
markdown 表格太不明显了

### ISSUE THREAD

**Issue by knmax** [rujews/maupassant-hugo#26]
markdown 表格太不明显了，看着感觉表格没生效

**Comment by skydamon** [comment]
希望可以给markdown的表格加上实线

**Comment by rujews** [comment]
截个图看看，我还没用过表格  @knmax

**Comment by knmax** [comment]
![image](https://user-images.githubusercontent.com/24750568/53536116-181cd800-3b40-11e9-8d16-119df0ece71d.png)

**Comment by knmax** [comment]
@rujews

**Comment by skydamon** [comment]
![image](https://user-images.githubusercontent.com/15014816/53536249-937e8980-3b40-11e9-912c-53deab03eb74.png)
我这边表格是看不到线的。。。

**Comment by skydamon** [comment]
> ![image](https://user-images.githubusercontent.com/15014816/53536249-937e8980-3b40-11e9-912c-53deab03eb74.png)
> 我这边表格是看不到线的。。。

运行环境：MacOS Mojave, hugo 0.54.0
使用Mac Chrome 72.0浏览。

**Comment by rujews** [comment]
@knmax  得截图是实际效果吗？这个效果看着可以啊。

@skydamon   你这个也是实际效果？

**Comment by skydamon** [comment]
@rujews 对，是实际效果
在flysnow.org搜到了一篇很久以前的博文，这个地方应该是表格吧，显示效果和我的一样
浏览环境：MacOS 10.14.3，Chrome 72.0
<https://www.flysnow.org/2017/04/08/go-in-action-go-identifier-export.html>
![image](https://user-images.githubusercontent.com/15014816/53854284-d7bbcf00-4003-11e9-9690-50670d0d2743.png)

**Comment by rujews** [comment]
恩，那调整下比较好   @skydamon
