### ISSUE TITLE
运行的时候出错

### ISSUE THREAD

**Issue by ngnetboy** [rujews/maupassant-hugo#27]
当运行 hugo server 的时候，报错如下：
Building sites … WARN 2019/02/15 17:25:38 Found no layout for "taxonomyTerm", language "en", output format "HTML": crea
te a template below /layouts with one of these filenames: tags/tag.terms.en.html.html, tags/terms.en.html.html, tags/lis
t.en.html.html, tags/tag.terms.html.html, tags/terms.html.html, tags/list.html.html, tags/tag.terms.en.html, tags/terms.
en.html, tags/list.en.html, tags/tag.terms.html, tags/terms.html, tags/list.html, taxonomy/tag.terms.en.html.html, taxon
omy/terms.en.html.html, taxonomy/list.en.html.html, taxonomy/tag.terms.html.html, taxonomy/terms.html.html, taxonomy/lis
t.html.html, taxonomy/tag.terms.en.html, taxonomy/terms.en.html, taxonomy/list.en.html, taxonomy/tag.terms.html, taxonom
y/terms.html, taxonomy/list.html, tag/tag.terms.en.html.html, tag/terms.en.html.html, tag/list.en.html.html, tag/tag.ter
ms.html.html, tag/terms.html.html, tag/list.html.html, tag/tag.terms.en.html, tag/terms.en.html, tag/list.en.html, tag/t
ag.terms.html, tag/terms.html, tag/list.html, _default/tag.terms.en.html.html, _default/terms.en.html.html, _default/lis
t.en.html.html, _default/tag.terms.html.html, _default/terms.html.html, _default/list.html.html, _default/tag.terms.en.h
tml, _default/terms.en.html, _default/list.en.html, _default/tag.terms.html, _default/terms.html, _default/list.html
WARN 2019/02/15 17:25:38 Found no layout for "section", language "en", output format "HTML": create a template below /la
youts with one of these filenames: 2019/2019.en.html.html, 2019/section.en.html.html, 2019/list.en.html.html, 2019/2019.
html.html, 2019/section.html.html, 2019/list.html.html, 2019/2019.en.html, 2019/section.en.html, 2019/list.en.html, 2019
/2019.html, 2019/section.html, 2019/list.html, section/2019.en.html.html, section/section.en.html.html, section/list.en.
html.html, section/2019.html.html, section/section.html.html, section/list.html.html, section/2019.en.html, section/sect
ion.en.html, section/list.en.html, section/2019.html, section/section.html, section/list.html, _default/2019.en.html.htm
l, _default/section.en.html.html, _default/list.en.html.html, _default/2019.html.html, _default/section.html.html, _defa
ult/list.html.html, _default/2019.en.html, _default/section.en.html, _default/list.en.html, _default/2019.html, _default
/section.html, _default/list.html

**Comment by Remonli** [comment]
遇到同样的问题了.

**Comment by rujews** [comment]
整理下日志格式，只发错误的就行，警告的不要发  @ngnetboy

**Comment by ngnetboy** [comment]
@rujews  您好，请问在哪里整理日志格式？新手，对这个不太了解。

**Comment by Remonli** [comment]
@rujews 跟楼主一样, 只有一大串warn, 没有error , 页面还是可以生成, 能不能看一下出这个warn 信息是因为设置少了啥么?

**Comment by rujews** [comment]
> @rujews 您好，请问在哪里整理日志格式？新手，对这个不太了解。

Issue  有`insert code`功能。

**Comment by rujews** [comment]
> @rujews 跟楼主一样, 只有一大串warn, 没有error , 页面还是可以生成, 能不能看一下出这个warn 信息是因为设置少了啥么?

可以正常生成就没事，这个警告是国际化得警告，当前主题不支持，不用理会
