### ISSUE TITLE
功能需求：浮动TOC和Latex支持

### ISSUE THREAD

**Issue by guader** [rujews/maupassant-hugo#3]
请问是否能在右侧增加浮动的TOC目录，和基于mathjax的latex支持？

**Comment by rujews** [comment]
@nampp TOC没有问题，周末可能会加上。不过latex用的多吗？这个安排的紧急程度没那么高。

**Comment by nampp** [comment]
谢谢，latex我自己加吧，比如涉及机器学习的内容会有公式的需求。

**Comment by rujews** [comment]
#4 多谢贡献，我看一下。

**Comment by liuhang93** [comment]
> @nampp TOC没有问题，周末可能会加上。不过latex用的多吗？这个安排的紧急程度没那么高。

请问toc功能加上了吗

**Comment by guader** [comment]
> > @nampp TOC没有问题，周末可能会加上。不过latex用的多吗？这个安排的紧急程度没那么高。
> 
> 请问toc功能加上了吗

哈哈好像没加，自己加吧。。。

**Comment by rujews** [comment]
的确，捂脸了  @liuhang93 @guader

**Comment by FeiChaoyu** [comment]
> > > @nampp TOC没有问题，周末可能会加上。不过latex用的多吗？这个安排的紧急程度没那么高。
> > 
> > 
> > 请问toc功能加上了吗
> 
> 哈哈好像没加，自己加吧。。。

怎么加？求助

**Comment by FeiChaoyu** [comment]
TOC能浮动吗，现在是固定的
