### ISSUE TITLE
分页问题

### ISSUE THREAD

**Issue by Alex-2017** [rujews/maupassant-hugo#33]
1.如何自定义每页显示条数?
config.toml中设置paginate=5无效
2.当文章数为9条时会分成两页,第二页没有文章显示(当前默认九条一页).

**Comment by rujews** [comment]
不是一个主题的吗？我这个主题默认是10个分页。

参考 https://gohugo.io/templates/pagination/

@Alex-2017

**Comment by Alex-2017** [comment]
大神,你好.

**Comment by Alex-2017** [comment]
大佬,你好.
我发现分页问题是因为/content/about/index.md.如果我删除了这个文件,分页功能正常.下面是我的一些配置.
`config.toml`
```
[[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "关于我"
    url = "/about/"
    weight = 3
```
`/content/about/index.md`
```
---
title: "关于我"
description: Java程序员
type: about
---
关于我内容简介.
```
我感觉是`index.md`的扉页配置出了问题.麻烦大佬抽空看下,非常感谢!

**Comment by Alex-2017** [comment]
大佬,你好.
我发现分页问题是因为/content/about/index.md.如果我删除了这个文件,分页功能正常.下面是我的一些配置.
`config.toml`
```
[[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "关于我"
    url = "/about/"
    weight = 3
```
`/content/about/index.md`
```
---
title: "关于我"
description: Java程序员
type: about
---
关于我内容简介.
```
我感觉是index.md的扉页配置出了问题.麻烦大佬抽空看下,非常感谢! @rujews

**Comment by Alex-2017** [comment]
大佬,你好.一页显示9条的问题解决了!原因是我没在content目录下创建about/index.md.
但是,当文章数为10条时,会显示2页,20条则3页.多出的一页没有文章列表.原因是因为content目录下存在的archives和about文件夹.如果删除这两个文件夹,分页就没有问题了,但是归档和关于的页面就不能跳转了.....
**content目录**
![image](https://user-images.githubusercontent.com/27010224/54907468-862aa400-4f20-11e9-9891-f5db7807d2b4.png)
**posts目录**
![image](https://user-images.githubusercontent.com/27010224/54907524-b2debb80-4f20-11e9-9722-9af7b99d741e.png)
**错误分页页面显示**
![image](https://user-images.githubusercontent.com/27010224/54907563-c853e580-4f20-11e9-9435-0ec43951f8c1.png)
`/content/about/index.md`
```
---
title: "关于我"
description: Java程序员
type: about
---
个人简介
```
`/content/archives/index.md`
```
---
title: "归档"
description: Java程序员
type: archives
[PersonalBlog.zip](https://github.com/rujews/maupassant-hugo/files/3002396/PersonalBlog.zip)

---
```
此次测试源码已上传到附件.
