### ISSUE TITLE
兼容 highlight.js

### ISSUE THREAD

**Issue by skywind3000** [rujews/maupassant-hugo#41]
[highlight.js](https://highlightjs.org) 是目前最好的语法高亮解决方案了。

我照着： http://note.qidong.name/2017/06/24/hugo-highlight/ 

的方法，把 maupassant 的 layouts/partials/head.html 拷贝到 layouts/partials/head.html 并且加了几行：

```html
<link href="https://cdn.bootcss.com/highlight.js/9.15.6/styles/monokai.min.css" rel="stylesheet">
<script src="https://cdn.bootcss.com/highlight.js/9.15.6/highlight.min.js"></script>
<link href="https://cdn.bootcss.com/highlight.js/9.15.6/styles/monokai.min.css" rel="stylesheet">
<script src="https://cdn.bootcss.com/highlight.js/9.15.6/highlight.min.js"></script>
<script src="https://cdn.bootcss.com/highlight.js/9.15.6/languages/vim.min.js"></script>
<script src="https://cdn.bootcss.com/highlight.js/9.15.6/languages/yaml.min.js"></script>
<script>hljs.initHighlightingOnLoad();</script>
```

再其他主题下工作正常，但是 maupassant 下面会有一层厚厚的边框：

![frame](https://user-images.githubusercontent.com/3035071/56081318-96a6ae00-5e3e-11e9-890e-25935ef50f7f.png)

看起来十分丑陋，请问有没有办法干掉这个厚厚的边框？？页面在：

http://localhost:1313/blog/archives/2193/

**Comment by rujews** [comment]
maupassant 有自带的语法高亮，直接用就可以了。
