### ISSUE TITLE
设置summaryLength自动获取的字数不对

### ISSUE THREAD

**Issue by 651016236** [rujews/maupassant-hugo#43]
设置summaryLength自动获取的字数不对，设置为3就显示了几十个字数

**Comment by LazyBonesLZ** [comment]
> summaryLength

加上 hasCJKLanguage = true 就可以解决。
[https://discourse.gohugo.io/t/limit-the-summary/4103/12](https://discourse.gohugo.io/t/limit-the-summary/4103/12)

**Comment by LazyBonesLZ** [comment]
加上 hasCJKLanguage = true 就可以解决。
https://discourse.gohugo.io/t/limit-the-summary/4103/12

**Comment by rujews** [comment]
恩，中日韩字符 @LazyBonesLZ
