### ISSUE TITLE
preserveTaxonomyNames和disablePathToLower选项无效

### ISSUE THREAD

**Issue by njudii** [rujews/maupassant-hugo#44]
如题，我在`` config.toml ``里设置了
```
preserveTaxonomyNames = true
disablePathToLower = true
```
然后发现我新建的一篇名为 "BerkeleyProgram"、标签为 "Berkeley" 的文章的URL依然是小写字母 "berkeleyprogram" ；侧边栏的tags和categories，以及文章下方的tags所对应的URL也都是小写字母。

**Comment by LazyBonesLZ** [comment]
> 如题，我在`config.toml`里设置了
> 
> ```
> preserveTaxonomyNames = true
> disablePathToLower = true
> ```
> 然后发现我新建的一篇名为 "BerkeleyProgram"、标签为 "Berkeley" 的文章的URL依然是小写字母 "berkeleyprogram" ；侧边栏的tags和categories，以及文章下方的tags所对应的URL也都是小写字母。

可能是你加错地方了？ 我刚开始也是这样，加在了[params]参数下了。后来加在的全局变量下就OK：
```
baseURL = "http://blog.harddone.com/"
languageCode = "zh-CN"
title = "ColofulDark Blog"
theme = "maupassant"
# 默认是70
summaryLength = 140
hasCJKLanguage = true
## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
## 是否禁止URL Path转小写
disablePathToLower = true
```

**Comment by njudii** [comment]
抱歉，我加到紧靠着theme下一行就可以了
