### ISSUE TITLE
最近文章的内容是可以自主选择的吗

### ISSUE THREAD

**Issue by skydamon** [rujews/maupassant-hugo#48]
发现你的博客上的最近文章的内容和最新的文章的内容是不一致的，最近发表的都是”工具“类别的文章，这些没有出现在最近文章里，请问这个是可以自主设置的吗？
![image](https://user-images.githubusercontent.com/15014816/57204898-4fe74680-6fed-11e9-95f7-7974979d11eb.png)

**Comment by rujews** [comment]
`工具`是一个新的section,最近文章只显示`post`,'posts'里的，所以没有显示
