### ISSUE TITLE
README内容错误

### ISSUE THREAD

**Issue by lethink** [rujews/maupassant-hugo#49]
我在按照README的使用过程中发现2处错误:

1.归档无法正确显示
参照[这里](https://github.com/JokerQyou/maupassant-hugo/blob/master/README_zh.md#%E5%AD%98%E6%A1%A3%E5%88%97%E8%A1%A8%E9%A1%B5%E9%9D%A2)，将`content/archives/index.md`文件内容改为：
```
---
title: "Archives"
type: "archives"
---
```
之后就能正常归档。
2.不蒜子页面计数器支持
按照README中添加配置，运行hugo会报错显示：
```
unmarshal failed: Near line xx (last key parsed ''): Key 'params' has already been defined.
```
在`config.toml`里正确的配置应该是:
```
[Params]
  busuanzi = true
```

**Comment by FeiChaoyu** [comment]
归档时自动生成的吗？为什么我配置还是空白页

**Comment by rujews** [comment]
一样哦，没看出来和我的README有什么区别，可以提一个PR吗？@lethink
