### ISSUE TITLE
文章内容长连接不自动换行

### ISSUE THREAD

**Issue by udpsec** [rujews/maupassant-hugo#5]
写了文章发现引用的链接过长就会突破原本的div，如图所示：
![image](https://user-images.githubusercontent.com/10917718/45592836-fc1ae500-b9aa-11e8-9f27-83eb1df67270.png)
可惜自己不懂hugo就会使用现成的不然就自己改了。
还有请问“本文为原创文章，转载注明出处，”每篇文章这一段是写文章的时候自己添加上去还是作者您写了通用的开关在config.toml里面呢

**Comment by udpsec** [comment]
分类categories 如果是全英文就可以显示正常，中英文就会显示404 比如Linux开发。 see also我这不显示。是根据文章名一样来显示吗还是同一个tags下。 突然提了好多issues。不好意思了

**Comment by rujews** [comment]
> 写了文章发现引用的链接过长就会突破原本的div，如图所示：
> ![image](https://user-images.githubusercontent.com/10917718/45592836-fc1ae500-b9aa-11e8-9f27-83eb1df67270.png)
> 可惜自己不懂hugo就会使用现成的不然就自己改了。
> 还有请问“本文为原创文章，转载注明出处，”每篇文章这一段是写文章的时候自己添加上去还是作者您写了通用的开关在config.toml里面呢

URL是特殊文本，不能换行，换行了就没法打开了，你可以把他转成短链接。
原创标记暂时还没有打算加，你可以自己先写到文章里。

**Comment by udpsec** [comment]
好的。今天自己加TOC加到心态爆炸不懂go模板的语法加不进去，上面的两个问题解决了感谢你，TOC可以您有时间可以更一波。

**Comment by rujews** [comment]
> 好的。今天自己加TOC加到心态爆炸不懂go模板的语法加不进去，上面的两个问题解决了感谢你，TOC可以您有时间可以更一波。

我试了下，样式不是满意，前端我不擅长，你有好的样式可以发出来，我试试看。

**Comment by wlh320** [comment]
感谢作者的工作，我前几天 fork 了一份自用，参考一个叫 even 的主题加了 TOC 功能，可供参考。不过我在用的过程中对主题其他地方也进行了修改和删除，没办法再 merge 了，就不提 pr 了。

顺便说一下使用主题中遇到的一些小细节问题，可供参考：

1. 回到顶部的 div 在 html 里面自带了 show 的 class，初始化会显示按钮，理论上应该滑动到一定的高度该按钮才会浮现吧？
2. 该主题用的 prism 主题是每一行背景色不同的，`style.css` 里面对代码字体大小的修改导致了代码行的大小和代码字体大小不匹配，代码行数多的时候能明显看到代码和行背景色错开。

**Comment by rujews** [comment]
> 感谢作者的工作，我前几天 fork 了一份自用，参考一个叫 even 的主题加了 TOC 功能，可供参考。不过我在用的过程中对主题其他地方也进行了修改和删除，没办法再 merge 了，就不提 pr 了。
> 
> 顺便说一下使用主题中遇到的一些小细节问题，可供参考：
> 
> 1. 回到顶部的 div 在 html 里面自带了 show 的 class，初始化会显示按钮，理论上应该滑动到一定的高度该按钮才会浮现吧？
> 2. 该主题用的 prism 主题是每一行背景色不同的，`style.css` 里面对代码字体大小的修改导致了代码行的大小和代码字体大小不匹配，代码行数多的时候能明显看到代码和行背景色错开。

的确，感谢反馈  @wlh320
