### ISSUE TITLE
收藏夹图标怎么设置

### ISSUE THREAD

**Issue by FeiChaoyu** [rujews/maupassant-hugo#54]

**Comment by rujews** [comment]
放个名字为favicon.ico的图标到static目录

**Comment by FeiChaoyu** [comment]
这个我放了，是网站Logo，不是收藏夹图标

**Comment by rujews** [comment]
网站什么logo？

**Comment by FeiChaoyu** [comment]
![image](https://user-images.githubusercontent.com/42114893/63159504-4d65a580-c04e-11e9-8c94-2a4eb6e6039d.png)

但是收藏夹图标没有

**Comment by rujews** [comment]
这个要看浏览器了吧，你看我的网站 www.flysnow.org 是否有？我自己用Google浏览器看是有的。

**Comment by FeiChaoyu** [comment]
![image](https://user-images.githubusercontent.com/42114893/63220590-b4ee3300-c1bd-11e9-9070-1823052f6cfc.png)
这是你的，我用IE firefox chrome看都没有

**Comment by rujews** [comment]
![image](https://user-images.githubusercontent.com/1407788/63399556-7b0e6e00-c403-11e9-988f-2d21678bbf08.png)

在上面这里 @FeiChaoyu

**Comment by FeiChaoyu** [comment]
收藏夹的图标没有

**Comment by FeiChaoyu** [comment]
但是收藏夹
![image](https://user-images.githubusercontent.com/42114893/63401253-35ed3a80-c409-11e9-9160-afac431ccfc3.png)mei这种没有

**Comment by rujews** [comment]
这个是早期的版本，被我去掉了，占地方。

**Comment by keob** [comment]
> 放个名字为favicon.ico的图标到static目录

请问是主题的static目录吗

**Comment by rujews** [comment]
你自己的static目录  @keob

**Comment by github-young** [comment]
> 但是收藏夹
> ![image](https://user-images.githubusercontent.com/42114893/63401253-35ed3a80-c409-11e9-9160-afac431ccfc3.png)mei这种没有

你在 `` static/css/style.css `` 里面加一段内容，具体可以看我的[这个commit](https://github.com/github-young/maupassant-hugo/commit/d4ad761d504567f6e8825294c3f3308ea186b409)
