### ISSUE TITLE
搜索功能有进展吗

### ISSUE THREAD

**Issue by FeiChaoyu** [rujews/maupassant-hugo#55]

**Comment by rujews** [comment]
有搜索的

**Comment by FeiChaoyu** [comment]
`search_provider = "google"`
我配了这个，但是搜索是空白
![image](https://user-images.githubusercontent.com/42114893/63438168-74611480-c45e-11e9-86f2-4ea4f9772bba.png)

**Comment by rujews** [comment]
应该你的网站还没被GOOGLE收录

**Comment by FeiChaoyu** [comment]
需要手动去提交吗？
还有一个问题：为什么我用百度搜索我的博客名搜索不到呢？

**Comment by rujews** [comment]
还是没有被收录

**Comment by CorPython** [comment]
@rujews 怎么添加在站内搜索博客

**Comment by rujews** [comment]
> @rujews 怎么添加在站内搜索博客

默认的有，参考我的 [https://www.flysnow.org/](https://www.flysnow.org/)

**Comment by CorPython** [comment]
我的意思是搜索自己写的文章,但是那个搜索指向的是搜索引擎




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "飞雪无情"<notifications@github.com&gt;; 
发送时间: 2019年11月23日(星期六) 晚上8:19
收件人: "rujews/maupassant-hugo"<maupassant-hugo@noreply.github.com&gt;; 
抄送: "寻路。"<1337425156@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [rujews/maupassant-hugo] 搜索功能有进展吗 (#55)



 
@rujews 怎么添加在站内搜索博客
  
默认的有，参考我的 https://www.flysnow.org/

**Comment by rujews** [comment]
没有，因为是静态的，不好实现  @CorPython

**Comment by CorPython** [comment]
好吧,我再想想办法




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "飞雪无情"<notifications@github.com&gt;; 
发送时间: 2019年11月23日(星期六) 晚上8:25
收件人: "rujews/maupassant-hugo"<maupassant-hugo@noreply.github.com&gt;; 
抄送: "寻路。"<1337425156@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [rujews/maupassant-hugo] 搜索功能有进展吗 (#55)




没有，因为是静态的，不好实现  @CorPython

**Comment by github-young** [comment]
@CorPython @rujews 
站内搜索可以看[这个主题的issue](https://github.com/xtfly/hugo-theme-next/issues/14)里面的search.js，是可以实现站内搜索的。不过bug就是我在这个issue里提出的。

**Comment by louissay** [comment]
> 没有，因为是静态的，不好实现 @CorPython

博主你好，考虑到google在国内被墙，我用algoliasearch实现了一个站内搜索的方案，替换了您之前的google搜索。具体可以查看 https://louissay.com 里到效果。

**Comment by CorPython** [comment]
@louissay 你的博客也不能搜索到自己的文章啊

**Comment by github-young** [comment]
> @louissay 你的博客也不能搜索到自己的文章啊

我上面回复的那个search.js可以实现站内搜索

**Comment by CorPython** [comment]
算了,没用,暂时不实现这个功能,改成bing搜索了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "YangXu"<notifications@github.com&gt;; 
发送时间: 2019年11月28日(星期四) 晚上8:37
收件人: "rujews/maupassant-hugo"<maupassant-hugo@noreply.github.com&gt;; 
抄送: "寻路。"<1337425156@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [rujews/maupassant-hugo] 搜索功能有进展吗 (#55)



 
@louissay 你的博客也不能搜索到自己的文章啊
  
我上面回复的那个search.js可以实现站内搜索

**Comment by rujews** [comment]
看来都是被强的原因，才都想要站内搜索  /捂脸

**Comment by rujews** [comment]
@FeiChaoyu @CorPython @github-young @louissay   可以使用站内搜索了，找到了一个办法实现，大家可以参考我的  [https://www.flysnow.org/](https://www.flysnow.org/)

**Comment by github-young** [comment]
@rujews 首先感谢一下，但是我发现这个站内搜索还是不能应用于形如 ``https://xxx.github.io/blog/ `` 这样的hugo站点，就是不把根目录`` xxx.github.io ``作为网址，而是用该帐号下的另一个repo作为网址。这个问题始终没有人解决，我之前看到的那个search.js也是这样。。。不知道您能不能解决

**Comment by rujews** [comment]
你看下，你的是不是提示找不到`index.xml`这个文件？@github-young

**Comment by github-young** [comment]
> 你看下，你的是不是提示找不到`index.xml`这个文件？@github-young

我如果把我的博客的网址改成`` xxx.github.io ``是可以实现站内搜索的，而且index.xml是生成的。

我发现`` xxx.github.io/blog/ ``不行的原因是在点击搜索按钮后，跳转的搜索页面的链接依然是`` xxx.github.io/search/ ``而不是`` xxx.github.io/blog/srarch ``，所以在想问题是不是出在`` single.html ``里面获取当前网站的`` baseUrl ``的那一步

**Comment by rujews** [comment]
确认个事情，你的baseUrl是不是`xxx.github.io/blog/`？如果是的话，我知道是什么问题，可以解决。

**Comment by github-young** [comment]
> 确认个事情，你的baseUrl是不是`xxx.github.io/blog/`？如果是的话，我知道是什么问题，可以解决。

是的，求教

**Comment by github-young** [comment]
> 确认个事情，你的baseUrl是不是`xxx.github.io/blog/`？如果是的话，我知道是什么问题，可以解决。

是的，请教

**Comment by rujews** [comment]
我要更新下主题的index.xml的路径为绝对路径

**Comment by louissay** [comment]
> @FeiChaoyu @CorPython @github-young @louissay 可以使用站内搜索了，找到了一个办法实现，大家可以参考我的 https://www.flysnow.org/

感谢~你的博客暂时访问不了。
我看了下提交的代码，并按照如下做了修改：

1. 检查`config.toml`的`disableKinds`配置项,是否禁用了RSS，如果禁用需要开启。
——没有设置disableKinds这个配置项
2. 在`config.toml`中找到`[params]`配置段落，增加`localSearch = true`开启站内搜索
——已添加
3. 在`content`目录下新建`search`目录,并且在`search`目录中新建`index.md`文件
——已添加

更新layouts/partials/search_form.html + layouts/search/single.html到最新

本地启动"hugo server -D"，搜索之后显示：

1年1月1日 |12284 阅读
---
title: "搜索"
description: "搜索页面"
type: "search"
---
赞赏

并没有显示结果。

**Comment by github-young** [comment]
> 我要更新下主题的index.xml的路径为绝对路径

我新建了个测试repo，可以看看问题的效果：<https://github-young.github.io/test/>。

不过我还观察到可能不仅仅是index.xml的绝对路径问题，我在本地`` hugo server ``预览时，输入一个词，点击搜索后，连搜索页面也不显示，并不是显示该词搜索不到，此时和index.xml没有联系。

**Comment by rujews** [comment]
试试，我推送了一个修复 @github-young

**Comment by github-young** [comment]
> 试试，我推送了一个修复 @github-young

我clone了最新的repo，试了发现部分有用，这也是奇怪的地方：这是测试的网页 <https://github-young.github.io/test/>，在这里我搜索 `` Test ``或`` test ``是可以搜到的，但是搜索`` Third ``或`` third ``或中文`` 第一 ``就搜不到，有点奇妙...

如果需要看源文件，在这里：<https://github.com/github-young/test>。谢谢
