### ISSUE TITLE
如何添加分类和标签啊?萌新完全看不懂go语言,还有归档中的页面会自动往首页显示这个bug

### ISSUE THREAD

**Issue by HiAugest** [rujews/maupassant-hugo#60]
谢谢大家了,走过路边救救孩子吧

**Comment by HiAugest** [comment]
这是我的配置文件设置
`baseURL = "http://www.flysnow.org"
languageCode = "zh-CN"
title = "八月的博客"
theme = "maupassant"                                        
 # 首页每页显示的文章数
paginate = 5    
## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
## 是否禁止URL Path转小写
disablePathToLower = true

##文章获取字数长度
summaryLength=15`

**Comment by HiAugest** [comment]
这是我的配置文件
baseURL = "http://www.flysnow.org"
languageCode = "zh-CN"
title = "八月的博客"
theme = "maupassant"                                        
// 首页每页显示的文章数
paginate = 5    
// 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
// 是否禁止URL Path转小写
disablePathToLower = true

//文章获取字数长度
summaryLength=15

**Comment by rujews** [comment]
这个是个主题，其他的教程，自己搜索Hugo看，网上大把。
