### ISSUE TITLE
站内搜索结果和预期不同

### ISSUE THREAD

**Issue by CorPython** [rujews/maupassant-hugo#69]
搜索有些tags或者目录时无搜索结果

**Comment by rujews** [comment]
看下这些tags或者目录是否在你的`http://example.com/index.xml`文件中  @CorPython

**Comment by CorPython** [comment]
@rujews 
你尝试在自己博客搜索gihub或者hugo关键字都没有结果,我的也是这种错误
![image](https://user-images.githubusercontent.com/44196120/70202850-ef241600-1755-11ea-8598-e29b47cde7bd.png)
![image](https://user-images.githubusercontent.com/44196120/70202857-fa774180-1755-11ea-99e6-cbd4bce23a4b.png)

**Comment by rujews** [comment]
不再这 `https://www.flysnow.org/index.xml` 里面的都搜索不到，此外目前区分大小写，我有时间再修复下。

**Comment by FeiChaoyu** [comment]
而且有些标题在index.xml也无法搜索。比如我的标题叫   **docker中容器之间通信的方式**，但是搜索 docker 找不到，但是搜索 容器 找到了

**Comment by ketchuppp** [comment]
@FeiChaoyu 我也发现了类似问题，经过测试，搜索时不能带上标题中的第一个字或字母，比如我要搜的标题叫Acwing，那么搜索时搜cwing才可以，不能带上标题中的第一个A；对你这个标题来说，搜索ocker中容器之间通信的方式，应该是能搜到的

**Comment by rujews** [comment]
看来JavaScript的函数indexOf很难满足搜索的功能。

**Comment by CorPython** [comment]
> 看来JavaScript的函数indexOf很难满足搜索的功能。
我看有些hugo博客用了hugo-lunr-diadpora来实现站内搜索,可是我不懂怎么使用

**Comment by CorPython** [comment]
@rujews 
我看有些hugo博客用了hugo-lunr-diadpora来实现站内搜索,可是我不懂怎么使用

**Comment by rujews** [comment]
原理差不多，它们是生成的JSON文件，用的也是JSON文件。我们用的是xml文件。

**Comment by CorPython** [comment]
@rujews 你可以试试用这个实现试试吗,我不大会前端

**Comment by rujews** [comment]
对于使用者，操作复杂

**Comment by CorPython** [comment]
好吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "飞雪无情"<notifications@github.com&gt;; 
发送时间: 2019年12月14日(星期六) 晚上8:47
收件人: "rujews/maupassant-hugo"<maupassant-hugo@noreply.github.com&gt;; 
抄送: "寻路。"<1337425156@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [rujews/maupassant-hugo] 站内搜索结果和预期不同 (#69)




对于使用者，操作复杂

**Comment by rujews** [comment]
问题修复了，不是`indexOf`，是我写的代码问题，判断应该是`>=0`，少了一个`=`，导致搜索字符串在首位的，都查找不到，也就是 @FeiChaoyu @ketchuppp 描述的现象。  @CorPython
