### ISSUE TITLE
hugo server 以后博客内容为空白

### ISSUE THREAD

**Issue by jdhao** [rujews/maupassant-hugo#7]
按照 http://www.flysnow.org/2018/07/29/from-hexo-to-hugo.html 上的说明进行配置，我的博客在 `content/posts/`, `content` 目录下还有 `about` 和 `archives` 目录，这两个目录下分别有一个 `index.md` 文件。

`about` 目录下 `index.md` 内容为：

```
---
title: "About"
type: about
---
```

`archives` 目录下 `index.md` 内容为：

```
---
title: "Archives"
type: archives
---
```

`config.toml` 的内容为

```
baseURL = "http://jdhao.github.io"
languageCode = "zh-CN"
title = "jdhao's blog"
theme = "maupassant"

preserveTaxonomyNames = true
disablePathToLower = true

[author]
  name = "jdhao"

[params]
  author = "jdhao"
  subtitle = "A blog for the patient people"

[menu]
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 3

[permalinks]
  post = "/:year/:month/:day/:title/"
```

生成的博客框架都有了，但是就是博客不显示，截图如下

![image](https://user-images.githubusercontent.com/16662357/46549981-476b4800-c906-11e8-9066-98ef8f60cf88.png)

**Comment by wlh320** [comment]
这个主题默认的文章目录好像是 `content/post` ，还有就是文章的 front matter 里的 `draft` 是否设置 ?

**Comment by rujews** [comment]
恩，默认文章目录是 `content/post`,你移动下文章到这个目录试试  @jdhao

**Comment by hellolijj** [comment]
我也遇到这个问题，后来将文章放在content/post/目录下就解决问题了，感谢

**Comment by rujews** [comment]
> 好的，谢谢大家回复，我回头试一下。另外为什么 content 下面的文件夹不固定，不同主题的要求不一样，不同主题迁移起来还是挺费事的。 Hexo 的话，`source` 目录下，就是 `_post`,`about`, `categories` 等目录，更换主题不需要动这些东西。

已兼容修复  @jdhao
