### ISSUE TITLE
代码高亮问题

### ISSUE THREAD

**Issue by CorPython** [rujews/maupassant-hugo#72]
![image](https://user-images.githubusercontent.com/44196120/70605848-3a4a9700-1c36-11ea-869e-a4abfc3f6e71.png)
sql语句的高亮没有显示出来,还有matlab代码也没有高亮

**Comment by rujews** [comment]
还不支持这些偏门的语言

**Comment by CorPython** [comment]
> 还不支持这些偏门的语言

@rujews sql应该还不算偏门语言吧
