### ISSUE TITLE
代码高亮字体变模糊，代码块变为黑色背景

### ISSUE THREAD

**Issue by NonAnaconda** [rujews/maupassant-hugo#73]
怎么设置成像作者的博客代码块一样显示效果？只要在markdown的代码块中标记上具体的语言（如：Go、Java），就会变成这样
![DeepinScreenshot_select-area_20191216200554](https://user-images.githubusercontent.com/50489280/70905890-07dad880-2040-11ea-8cc5-139f9481f67f.png)
怎么解决呢？

**Comment by rujews** [comment]
你是否用了自定义的样式？我的源代码一般是这么写的，没有问题。

```go
func main() {
	r := gin.Default()
	r.POST("/", func(c *gin.Context) {
		wechat := c.PostForm("wechat")
		c.String(200, wechat)
	})

	r.Run(":8080")
}
```

**Comment by NonAnaconda** [comment]
感谢作者的解答，我没有使用自定义的CSS&JS，在出现这种问题之前提交文章都是显示正常的，出现问题的原因是在我利用hugo生成新的markdown类型文章时，使用了typora编辑器中的Night主题编辑了此文章（之前都是在使用Github主题），结果发布到服务器上之后出现了这种问题。

**Comment by rujews** [comment]
如果你的是干净的MD文档，不带HTML和CSS，按说不应该，这个需要你看下你的HTML源代码，查查是哪些CSS样式影响了 @NonAnaconda

**Comment by NonAnaconda** [comment]
不知为何多出了一些行间，如图：
![DeepinScreenshot_select-area_20191217144414](https://user-images.githubusercontent.com/50489280/70971482-0d85fc00-20dc-11ea-83a7-4670315bd270.png)
但是我不知道如何修改。。。查看了了静态文件，修改了pre的样式，但是只对没有标识语言的代码块起作用，也查看了js，但是是压缩的，没看懂。修改的css样式为下图：
![DeepinScreenshot_select-area_20191217145118](https://user-images.githubusercontent.com/50489280/70971802-b92f4c00-20dc-11ea-82ab-9e204e0b1b8e.png)
具体的config如下：
`
theme = "maupassant"

保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
 是否禁止URL Path转小写
disablePathToLower = true

disableKinds = false
hasCJKLanguage = true
summaryLength = 140


[author]
  name = "Anaconla"

[params]
  author = "Anaconla"
  subtitle = "Python,Golang,Manjaro"
  keywords = "Python,Golang,Manjaro"
  description = "Python,Golang,Manjaro"
  busuanzi = true
  localSearch = true

[menu]

  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 3
    


[[params.links]]
  title = "Android Gradle权威指南"
  name = "Android Gradle权威指南"
  url = "#"
[[params.links]]
  title = "常用开发工具CDN镜像"
  name = "常用开发工具CDN镜像"
  url = "#"   
  

`
baseURL和title这些不会出问题。。。

**Comment by rujews** [comment]
是不是用了hugo的highlight?贴下你的md文件 @NonAnaconda

**Comment by NonAnaconda** [comment]
---
title: "Test"
date: 2019-12-17T14:39:22+08:00
description: ""
draft: false
tags: []
categories: []

---

```go
func main() {
	r := gin.Default()

	r.GET("/", func(c *gin.Context) {
		c.String(200, c.Query("wechat"))
	})
	r.Run(":8080")
}
```

**Comment by CaiJingLong** [comment]
所以最后怎么解决的?

**Comment by CaiJingLong** [comment]
原图:
![image](https://user-images.githubusercontent.com/14145407/72035702-97884580-32d3-11ea-87ac-f105fcbda795.png)

---
解决方案1: 
经查, pre标签的style中多了一个背景颜色, 可以将这个去掉, 会变成浅色背景

![image](https://user-images.githubusercontent.com/14145407/72035548-319bbe00-32d3-11ea-8689-03a1c0b1bc43.png)

删除后效果:


![image](https://user-images.githubusercontent.com/14145407/72035825-ecc45700-32d3-11ea-92c9-be21f9636545.png)

--

解决方案2: 

修改prism.css 
将 `pre[class*="language-"]` 标签 中的color和text-shadow删除, 是深色系, 但是等于号会比较怪

![image](https://user-images.githubusercontent.com/14145407/72035940-488ee000-32d4-11ea-8995-104e66ef60dd.png)


---

所以建议还是使用第一个解决方案, 找到这个pre标签是在哪里定义的, 然后把这个颜色去掉即可

**Comment by rujews** [comment]
解决了啊，23天前已经被  https://github.com/flysnow-org/maupassant-hugo/commit/65a159812033d8f6002d8f3105d02f534aa3b0a4  关闭了，你用最新的主题模板就可以了  @CaiJingLong
