### ISSUE TITLE
代码块copy按钮位置不在代码块内部

### ISSUE THREAD

**Issue by ketchuppp** [rujews/maupassant-hugo#74]
前几天将您的代码复制功能移植到自己博客中，原封不动移植后，代码块copy按钮，在代码块内部；但同时您似乎也修改了代码块的字体大小，我将字体大小调回去后，copy出现在了代码块的下面。[如下链接](https://ketchuppp.xyz/post/acwing367-%E5%AD%A6%E6%A0%A1%E7%BD%91%E7%BB%9C/)
请问是否是因为字体大小影响了这一点呢

**Comment by ketchuppp** [comment]
现已经解决，又是我的失误

**Comment by wenjy** [comment]
@ketchuppp 代码复制怎么弄的啊？
